import { View, Text, TextInput, TouchableOpacity } from 'react-native'
import React, { useState, useContext, useEffect } from 'react'
import styles from './styles'
import axios from 'axios'
import { useNavigation } from '@react-navigation/native'